name: Validate Commit Messages

on:
  push:
    branches:
      - '*'

jobs:
  commitMessage:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit messages
        run: |
          pattern="\$[A-Z]+-\d+"
          git log --pretty=format:"%s" ${{ github.event.before }}..${{ github.sha }} | grep -vE "$pattern" || exit 0
          echo "Invalid commit message"
          exit 1

